Day-41 - matplotlib and data visualization

In [2]:
import pandas as pd

In [3]:
marks = [45,65,23,45]
d = pd.Series(marks)
print(d)
print(d.dtype)
print(d.ndim)
print(d.shape)
print(type(d))
print(type(d.dtypes))

0    45
1    65
2    23
3    45
dtype: int64
int64
1
(4,)
<class 'pandas.Series'>
<class 'numpy.dtypes.Int64DType'>

In [4]:
stu = {"Name":"Jaga","Age":22,"place":"Hyd"}
e = pd.Series(stu)
print(e)
print(e.index)
print(e.dtype)
print(e.ndim)
print(e.shape)
print(type(e))
print(type(e.dtypes))

Name     Jaga
Age        22
place     Hyd
dtype: object
Index(['Name', 'Age', 'place'], dtype='str')
object
1
(3,)
<class 'pandas.Series'>
<class 'numpy.dtypes.ObjectDType'>

In [5]:
data = {"names":["AAA","PFS","JFS","DA","DS"],"ids":[12,43,56,78,67]}
f = pd.Series(data)
print(f)
print(f.index)
print(f.dtype)
print(f['names'])
print(f['ids'])
print(f['names'][2])
print(f['ids'][:2])
print(f['ids'])

names    [AAA, PFS, JFS, DA, DS]
ids         [12, 43, 56, 78, 67]
dtype: object
Index(['names', 'ids'], dtype='str')
object
['AAA', 'PFS', 'JFS', 'DA', 'DS']
[12, 43, 56, 78, 67]
JFS
[12, 43]
[12, 43, 56, 78, 67]

In [6]:
# sclaer values   it taking default as Zero index in df for int

data = 6
g=pd.Series(data)
print(g)
h = pd.Series(data,index=['rank'])
print(h)

0    6
dtype: int64
rank    6
dtype: int64

In [7]:
# sclaer values   it taking default as Zero index in df for str

data = 'Codegnan'

g=pd.Series(data)
print(g)
h = pd.Series(data,index=['rank'])
print(h)

0    Codegnan
dtype: str
rank    Codegnan
dtype: str

In [8]:
marks = [45,65,23,45]
z = pd.DataFrame(marks)
z
print(z)
print(z.index);print(z.columns)
k = pd.DataFrame(marks,columns=['Marks'])
print(k)
print(k.shape)
print(k.size)
print(k.ndim)

    0
0  45
1  65
2  23
3  45
RangeIndex(start=0, stop=4, step=1)
RangeIndex(start=0, stop=1, step=1)
   Marks
0     45
1     65
2     23
3     45
(4, 1)
4
2

In [9]:
data = {"names":["AAA","PFS","JFS","DA","DS"],"ids":[12,43,56,78,67]}
f = pd.DataFrame(data)
f

  names  ids
0   AAA   12
1   PFS   43
2   JFS   56
3    DA   78
4    DS   67

In [10]:
details = {"Products":["Mobile","Laptop","Earphones","headphones"],"Sales":[60000,50000,500000,350000],"Stocks":[10,6,35,55]}

d = pd.DataFrame(details)
d
print(d.shape)
print(d.size)
print(d.ndim)
print(type(d))
print(d.dtypes)
print(d.select_dtypes(['int']))

(4, 3)
12
2
<class 'pandas.DataFrame'>
Products      str
Sales       int64
Stocks      int64
dtype: object
    Sales  Stocks
0   60000      10
1   50000       6
2  500000      35
3  350000      55

In [11]:
d['Products']
d[['Products','Sales','Stocks']]
d.Products

0        Mobile
1        Laptop
2     Earphones
3    headphones
Name: Products, dtype: str

In [12]:
# Acessing Row wise Data -- index -->loc(),filter()

d.index

RangeIndex(start=0, stop=4, step=1)

In [14]:
print(d.loc[0]) # locate indexing values
print(d.loc[0]['Products'])
print()
print(d.loc[0][['Stocks','Sales']])
print()
print(d.loc[[2,0]])
print()
print(d.loc[[2,0]],[['Products','Stocks']])
print()
print(d.loc[2, 'Stocks'])

Products    Mobile
Sales        60000
Stocks          10
Name: 0, dtype: object
Mobile

Stocks       10
Sales     60000
Name: 0, dtype: object

    Products   Sales  Stocks
2  Earphones  500000      35
0     Mobile   60000      10

    Products   Sales  Stocks
2  Earphones  500000      35
0     Mobile   60000      10 [['Products', 'Stocks']]

35

In [15]:
# iloc --> selection by pos 

print(d.index)

print(d.iloc[0])
print()
print(d.iloc[[2,3]])
print()
print(d.iloc[[2,3]],[['Stocks','Products']])

RangeIndex(start=0, stop=4, step=1)
Products    Mobile
Sales        60000
Stocks          10
Name: 0, dtype: object

     Products   Sales  Stocks
2   Earphones  500000      35
3  headphones  350000      55

     Products   Sales  Stocks
2   Earphones  500000      35
3  headphones  350000      55 [['Stocks', 'Products']]

In [16]:
# Complete info abot df
print(d.info())

# summeray of df 
print(d.describe())

print(d.describe(include='object'))


# top --. most repeating Values

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Products  4 non-null      str
 1   Sales     4 non-null      int64
 2   Stocks    4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes
None
               Sales     Stocks
count       4.000000   4.000000
mean   240000.000000  26.500000
std    222261.107709  22.927422
min     50000.000000   6.000000
25%     57500.000000   9.000000
50%    205000.000000  22.500000
75%    387500.000000  40.000000
max    500000.000000  55.000000
       Products
count         4
unique        4
top      Mobile
freq          1

C:\Users\boyal\AppData\Local\Temp\ipykernel_19416\3977403851.py:7: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(d.describe(include='object'))

In [17]:
d['Sales'] = d['Sales'].astype('float')
print(d['Sales'].info())

<class 'pandas.Series'>
RangeIndex: 4 entries, 0 to 3
Series name: Sales
Non-Null Count  Dtype
--------------  -----
4 non-null      float64
dtypes: float64(1)
memory usage: 164.0 bytes
None

In [18]:
# groupby()

d.groupby('Products')['Sales'].mean()
print()

Products
Earphones     500000.0
Laptop         50000.0
Mobile         60000.0
headphones    350000.0
Name: Sales, dtype: float64

In [19]:
d.groupby('Products')['Sales'].sum()

Products
Earphones     500000.0
Laptop         50000.0
Mobile         60000.0
headphones    350000.0
Name: Sales, dtype: float64

In [4]:
import pandas as pd
pd.read_csv("Products.csv").head()

             Product     Brand  Price  Stock  BestSeller
0            Monitor  EchoBoom  43625    182        True
1  Bluetooth Speaker  SoundMax  10067    117        True
2             Laptop   SkyLink  65982    152       False
3             Webcam  EchoBoom  44852    115       False
4         Headphones  TechNova  53477     61       False

In [3]:
data = pd.read_csv("Products.csv")
data.head()

             Product     Brand  Price  Stock  BestSeller
0            Monitor  EchoBoom  43625    182        True
1  Bluetooth Speaker  SoundMax  10067    117        True
2             Laptop   SkyLink  65982    152       False
3             Webcam  EchoBoom  44852    115       False
4         Headphones  TechNova  53477     61       False